{% set version="1.0.0" %}
{% set name="beamspy" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/computational-metabolomics/{{ name|lower }}
  git_tag: 'v{{ version }}'

build:
  noarch: python
  number: 0
  entry_points:
    - beamspy = beamspy.__main__:main
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - python >3.7
    - setuptools
    - requests ==2.22.0
    - numpy ==1.17.1
    - scipy ==1.3.1
    - networkx ==2.4
    - pandas ==0.25.0
    - seaborn ==0.9.0
    - pyteomics ==4.1.2
    - biopython ==1.74
    - matplotlib ==3.1.1
    - pyside2 ==5.13.1
    - tqdm
  run:
    - python >3.7
    - setuptools
    - requests ==2.22.0
    - numpy ==1.17.1
    - scipy ==1.3.1
    - networkx ==2.4
    - pandas ==0.25.0
    - seaborn ==0.9.0
    - pyteomics ==4.1.2
    - biopython ==1.74
    - matplotlib ==3.1.1
    - pyside2 ==5.13.1
    - tqdm
test:
  imports:
    - beamspy
  commands:
    - beamspy --help

about:
  home: https://github.com/computational-metabolomics/beamspy
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: LICENSE
  summary: BEAMSpy - Birmingham mEtabolite Annotation for Mass Spectrometry (Python package)

extra:
  recipe-maintainers:
    - RJMW
