{% set version = "1.3.0" %}
{% set name = "rRDPData" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: ca3b09dc38c01b2760d327ac92fd622e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# SystemRequirements: Java
requirements:
  host:
    - 'bioconductor-rrdp >=1.18.0,<1.19.0'
    - r-base
    - openjdk 8.*
  run:
    - 'bioconductor-rrdp >=1.18.0,<1.19.0'
    - r-base
    - curl
    - openjdk 8.*
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-2
  summary: 'Database used by the default RDP Classifier'

