{% set version = "1.13.0" %}
{% set name = "QDNAseq.mm10" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 9fba3bfb64443ddc7fb989b6b7cfcaa3
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-qdnaseq >=1.20.0,<1.21.0'
    - r-base
  run:
    - 'bioconductor-qdnaseq >=1.20.0,<1.21.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL
  summary: 'This package provides QDNAseq bin annotations for the mouse genome build mm10.'
extra:
  parent_recipe:
    name: bioconductor-qdnaseq.mm10
    path: recipes/bioconductor-qdnaseq.mm10
    version: 1.10.0

