package:
  name: cramtools
  version: "3.0"

source:
  url: https://github.com/enasequence/cramtools/blob/master/cramtools-3.0.jar
  sha256: 1f7eb4555113d7c0924fceb0869af6e5d41b76c7f67d0dfb691031c165102adb
  #url: https://github.com/enasequence/cramtools/raw/27ed5c0368f7a64ee2eba705d8c666d35630ebfc/cramtools-2.1.jar

build:
  number: 0
  noarch: generic

requirements:
  run:
    - openjdk

test:
  commands:
    - cramtools -h

about:
  home: http://www.ebi.ac.uk/ena/software/cram-toolkit
  license: Apache v2.0
  summary: A set of Java tools and APIs for efficient compression of sequence read data

extra:
  identifiers:
    - biotools:CRAMTools
