package:
  name: crispresso2
  version: "2.0.33"

build:
  number: 0
  skip: True # [not py27]

source:
  url: https://github.com/pinellolab/CRISPResso2/archive/v2.0.33.tar.gz
  sha256: b7dbe6f51e84d827cb2ca6d0883f00b964d42142e40b8960aa35044ae1c345a1


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - scipy 1.1.0
    - numpy >=1.9
    - pandas >=0.15,<=0.24
    - matplotlib-base >=1.3.1
    - biopython >=1.6.5
    - argparse
    - jinja2
    - trimmomatic
    - flash
    - samtools
    - bowtie2
    - seaborn 0.7.1
    - networkx 2.2
  run:
    - python
    - scipy 1.1.0
    - numpy >=1.9
    - pandas >=0.15,<=0.24
    - matplotlib-base >=1.3.1
    - biopython >=1.6.5
    - argparse
    - jinja2
    - trimmomatic
    - flash
    - samtools
    - bowtie2
    - seaborn 0.7.1
    - networkx 2.2

test:
  imports:
    - CRISPResso2
  commands:
    - CRISPResso -h

about:
  home: https://github.com/pinellolab/CRISPResso2
  license: Partners
  license_file: LICENSE.txt
  summary: "A software pipeline designed to enable rapid and intuitive interpretation of genome editing experiments"
