{% set version = "1.19.0" %}
{% set name = "MMDiffBamSubset" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: db10803b53b95f7e115a21d34fc4c067
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: MMDiff2
requirements:
  host:
    - r-base
  run:
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: LGPL
  summary: 'Subset of BAM files, including WT_2.bam, Null_2.bam, Resc_2.bam, Input.bam from the "Cfp1" experiment (see Clouaire et al., Genes Dev. 2012). Data is available under ArrayExpress accession numbers E-ERAD-79. Additionally, corresponding subset of peaks called by MACS'

