{% set version = "2.5.8" %}
{% set sha256 = "df528ba5cd86071017a005ae9a7cd76f8d35b7270e62840ae5fc4231092ac9b8" %}

package:
  name: hyphy
  version: '{{ version }}'

source:
  url: https://github.com/veg/hyphy/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 2

requirements:
  build:
    - cmake
    - '{{ compiler("cxx") }}'
    - openmpi
  host:
    - curl
    - openmpi
  run:
    - curl
    - openmpi

test:
  files:
    - slac_input.fa
    - slac_input.nhx
  commands:
    - hyphy --help
    - hyphy slac --alignment slac_input.fa --tree slac_input.nhx --code 'Universal' --branches 'All' --samples '100' --pvalue '0.1' --output slac_output.json

about:
  home: http://hyphy.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "An open-source software package for comparative sequence analysis using stochastic evolutionary models."
  description: |
    HyPhy (Hypothesis Testing using Phylogenies) is an open-source software package for the analysis of genetic sequences
    (in particular the inference of natural selection) using techniques in phylogenetics, molecular evolution, and machine learning.
  dev_url: https://github.com/veg/hyphy

extra:
  container:
    extended-base: true
