{% set version = "3.1.1" %}

package:
  name: "ont-fast5-api"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/o/ont-fast5-api/ont-fast5-api-{{ version }}.tar.gz
  sha256: ce5a955c5e90a393f040fb36fc461382339fc0b9cd63e3969b9763127dc2b0d3

build:
  noarch: python
  number: 0
  entry_points:
    - multi_to_single_fast5=ont_fast5_api.conversion_tools.multi_to_single_fast5:main
    - single_to_multi_fast5=ont_fast5_api.conversion_tools.single_to_multi_fast5:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - h5py >=2.6
    - numpy >=1.11
    - progressbar33 >=2.3.1
    - python
    - six >=1.9
    - packaging

test:
  imports:
    - ont_fast5_api
    - ont_fast5_api.analysis_tools
    - ont_fast5_api.conversion_tools
  commands:
    - multi_to_single_fast5 --help
    - single_to_multi_fast5 --help

about:
  home: https://github.com/nanoporetech/ont_fast5_api
  license: Mozilla Public 2.0 (MPL 2.0)
  license_family: OTHER
  license_file: LICENSE.md
  summary: Oxford Nanopore Technologies fast5 API software
