{% set name = "lace" %}
{% set version = "1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/Oshlack/Lace/archive/v{{ version }}.tar.gz
  sha256: 0edde43e92bd9b62710ce5d4a1da00e0cf5ada1fbf534804956f4ed34504d75b
  patches:
    - lace.patch

requirements:
  build:
  - {{ compiler('c') }}
  run:
  - python
  - pandas
  - networkx
  - numpy
  - matplotlib
  - blat

test:
  commands:
    - Lace.py -h
    - Lace_Checker.py -h
    - Mobius.py -h
    - STViewer.py -h
    - BuildSuperTranscript.py

about:
  home: https://github.com/Oshlack/Lace
  license: GPL3
  license_file: LICENSE
  summary: 'Building SuperTranscripts: A linear representation of transcriptome data'

extra:
  notes: "Prefix with 'Lace_' for the script name that is rather generic: 'Checker.py'."
