{% set name = "lace" %}
{% set version = "1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/dpryan79/Lace
  git_tag: python_module
  # This should get converted once https://github.com/Oshlack/Lace/pull/49 is merged
#  url: https://github.com/Oshlack/Lace/archive/v{{ version }}.tar.gz
#  sha256: 0edde43e92bd9b62710ce5d4a1da00e0cf5ada1fbf534804956f4ed34504d75b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - pandas
    - networkx
    - numpy
    - matplotlib
    - blat

test:
  commands:
    - Lace -h
    - Lace_Checker -h
    - Mobius -h
    - STViewer -h
    - BuildSuperTranscript 2>&1 | grep "Function takes"

about:
  home: https://github.com/Oshlack/Lace
  license: GPL3
  license_file: LICENSE
  summary: 'Building SuperTranscripts: A linear representation of transcriptome data'

extra:
  notes: "Prefix with 'Lace_' for the script name that is rather generic: 'Checker.py'."
