{% set version = "1.2.0" %}
{% set name = "Rcwl" %}
{% set bioc = "3.10" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 15edaaf62161b758c81b3c7594ac21ee
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: testthat, knitr, rmarkdown, BiocStyle
# SystemRequirements: python (>= 2.7), cwltool (>= 1.0.2018)
requirements:
  host:
    - 'bioconductor-biocparallel >=1.20.0,<1.21.0'
    - 'bioconductor-s4vectors >=0.24.0,<0.25.0'
    - r-base
    - r-batchtools
    - r-codetools
    - r-diagrammer
    - r-r.utils
    - r-shiny
    - r-yaml
    - 'python >=2.7'
  run:
    - 'bioconductor-biocparallel >=1.20.0,<1.21.0'
    - 'bioconductor-s4vectors >=0.24.0,<0.25.0'
    - r-base
    - r-batchtools
    - r-codetools
    - r-diagrammer
    - r-r.utils
    - r-shiny
    - r-yaml
    - 'python >=2.7'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL-2 | file LICENSE'
  summary: 'Wrap Command Tools and Pipelines Using CWL'
  description: 'The package can be a simple and user-friendly way to manage command line tools and build data analysis pipelines in R using Common Workflow Language (CWL).'
  license_file: LICENSE

