package:
  name: ragout
  version: 2.3

source:
  url: https://github.com/fenderglass/Ragout/archive/master.tar.gz
  sha256: 5f71f491228cf04237781762f01ff365125d986a2873c8116222a395e5f01317

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - setuptools
  host:
    - python
    - setuptools
  run:
    - python
    - decorator ==4.3.0
    - networkx ==2.2
    - sibelia
    - setuptools

extra:
  skip-lints:
    - uses_setuptools  #uses pkg_resources

test:
  commands:
    - ragout -h
    - Sibelia --version

about:
  home: https://github.com/fenderglass/Ragout
  license: GPLv3
  summary: "Chromosome-level scaffolding using multiple references"
