package:
  name: ragout
  version: 2.3

source:
  url: https://github.com/fenderglass/Ragout/archive/master.tar.gz
  sha256: 9406a60ff01e9d63d7f36173903993e674fa847be1933e85dacb9ec7de92ec0e

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - python
  run:
    - python
    - decorator ==4.3.0
    - networkx ==2.2
    - sibelia

test:
  commands:
    - ragout -h
    - Sibelia --version

about:
  home: https://github.com/fenderglass/Ragout
  license: GPLv3
  summary: "A tool for chromosome-level scaffolding using multiple references"
