package:
  name: ragout
  version: 2.3

source:
  url: https://github.com/fenderglass/Ragout/archive/master.tar.gz
  sha256: c0d371932000113835bdcccd63ec3bec607d62cc7c0d35c903625bd84307fbd7

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - python
  run:
    - python
    - decorator ==4.3.0
    - networkx ==2.2
    - sibelia

test:
  commands:
    - ragout -h
    - Sibelia --version

about:
  home: https://github.com/fenderglass/Ragout
  license: GPLv3
  summary: "A tool for chromosome-level scaffolding using multiple references"
