package:
  name: lofreq
  version: '2.1.3.1'
source:
  url: https://github.com/CSB5/lofreq/blob/master/dist/lofreq_star-2.1.3.1.tar.gz?raw=true
  sha256: 0caddc6163641993a71c8b94a145debcbf3b63ac969eeaf4fab297ff50817623
build:
  number: 2
requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - samtools
    - htslib
  run:
    - python
test:
  commands:
    - 'lofreq version'
about:
  home: http://csb5.github.io/lofreq/
  license: MIT
  summary: A fast and sensitive variant-caller for inferring SNVs and indels from next-generation sequencing data
