{% set version = "0.1.11" %}

package:
  name: dwgsim
  version: {{ version }}

source:
  - url: https://github.com/nh13/DWGSIM/archive/dwgsim.{{ version }}.tar.gz
    sha256: 49e4b558e313f4cd5755961f7f24ba48ad580c0324772d7080b59cb69ce0148b
    patches:
      #- dwgsim.patch, haven't written yet.
  - git_url: http://github.com/samtools/samtools
    folder: samtools
    git_rev: 28391e5898804ce6b805016d8c676fdf61442eb3
    patches:
      - samtools.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
    - ncurses
  run:
    - zlib
    - ncurses

test:
  commands:
    - printf ">a\nAAAAA" > ref.fa; dwgsim ref.fa pref

about:
  home: https://github.com/nh13/DWGSIM
  license: GNU General Public License v2 (GPLv2)
  license_family: GPL
  license_file: LICENSE
  summary: 'Whole Genome Simulator for Next-Generation Sequencing'

extra:
  identifiers:
    - biotools:dwgsim
