{% set version = "1.19.0" %}
{% set name = "Fletcher2013b" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 43f651f8b7b3e9d7c3a9e03441c53665
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-fletcher2013a >=1.19.0,<1.20.0'
    - 'bioconductor-reder >=1.32.0,<1.33.0'
    - 'bioconductor-rtn >=2.8.0,<2.9.0'
    - r-base
    - r-igraph
    - r-rcolorbrewer
  run:
    - 'bioconductor-fletcher2013a >=1.19.0,<1.20.0'
    - 'bioconductor-reder >=1.32.0,<1.33.0'
    - 'bioconductor-rtn >=2.8.0,<2.9.0'
    - r-base
    - r-igraph
    - r-rcolorbrewer
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'This package reproduces the systems biology analysis for the data in package Fletcher2013a using RTN.'

