{% set name = "OBITools" %}
{% set version = "3.0.0-beta3" %}
{% set sha256 = "e06c6a4c4a2985a5418fdf051bdea7a87443e2ba5ee5a58f4d5a0b13e306e287" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://git.metabarcoding.org/obitools/obitools3/repository/{{ version }}/archive.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not py27]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.6
    - cython
  run:
    - python >=3.6

test:
  commands:
    - obi -h
    - obi import -h
    - obi ls -h
    - obi less -h
    - obi alignpairedend -h
    - obi grep -h
    - obi ngsfilter -h
    - obi uniq -h
    - obi annotate -h
    - obi clean -h
    - obi ecopcr -h
    - obi ecotag -h
    - obi stats -h
    - obi align -h
    - obi history -h
    - obi export -h

about:
  home: https://metabarcoding.org/obitools3
  license: CeCILL-V2
  license_file: '{{ RECIPE_DIR }}/LICENSE'
  summary: "The OBITools package is a set of programs specifically designed for analyzing NGS data in a DNA metabarcoding context, taking into account taxonomic information"
