{% set name = "OBITools" %}
{% set version = "3.0.0-beta5" %}
{% set sha256 = "62f1222bb274db765d592ebc43c84c4ae57bf4e7de9433d2ea098a5a297acc01" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://git.metabarcoding.org/obitools/obitools3/repository/v{{ version }}/archive.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py27]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
  host:
    - python
    - cython
  run:
    - python

test:
  commands:
    - obi -h
    - obi import -h
    - obi ls -h
    - obi less -h
    - obi alignpairedend -h
    - obi grep -h
    - obi ngsfilter -h
    - obi uniq -h
    - obi annotate -h
    - obi clean -h
    - obi ecopcr -h
    - obi ecotag -h
    - obi stats -h
    - obi align -h
    - obi history -h
    - obi export -h

about:
  home: https://metabarcoding.org/obitools3
  license: CeCILL-V2
  license_file: 'LICENSE'
  summary: "The OBITools package is a set of programs specifically designed for analyzing NGS data in a DNA metabarcoding context, taking into account taxonomic information"
