{% set name = "scvelo" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e56235bd83bbcc03234b70ce7b1b2f2f2c5b7a89f8e654d9ae1f7872412b5d36

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - anndata >=0.6.18
    - loompy >=2.0.12
    - matplotlib >=2.2
    - numpy >=1.17
    - pandas >=0.23
    - python >=3.6
    - scanpy >=1.4
    - scikit-learn >=0.21.2
    - scipy >=1.0
    - umap-learn >=0.3

test:
  imports:
    - scvelo
    - scvelo.archive
    - scvelo.archive.api
    - scvelo.plotting
    - scvelo.preprocessing
    - scvelo.tools

about:
  home: "https://github.com/theislab/scvelo"
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "single-cell RNA velocity generalized to transient cell states"
