{% set version = "2.2.0" %}

package:
  name: crispritz
  version: {{ version }}

source:
  url: https://github.com/pinellolab/CRISPRitz/archive/v{{ version }}.tar.gz
  sha256: aa5eb34792f8dbbf6aa851feb9fe61e6b17f274151c526c8f3c7cd6aad287265
  
build:
  number: 0

requirements:
  build:
    - {{compiler('cxx')}}
    - make
    - boost
    - openmp
    
  host:
    - dash =1.1.1
    - dash-renderer =1.0.1
    - dash-daq =0.1.7
    - flask-caching =1.7.2
    - rename
    - dash-bootstrap-components
    - poppler
    - bedtools
    - scikit-learn =0.21.2
    - biopython
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftools
    - boost
    - tk
    - openmp
    - libdeflate
    - libcxx
    - python =3.6
    
  run:
    - dash =1.1.1
    - dash-renderer =1.0.1
    - dash-daq =0.1.7
    - flask-caching =1.7.2
    - rename
    - dash-bootstrap-components
    - poppler
    - bedtools
    - scikit-learn =0.21.2
    - biopython
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftools
    - boost
    - tk
    - openmp
    - libdeflate
    - libcxx
    - python =3.6
    
test:
  commands:
    - crispritz.py

about:
  home: https://github.com/pinellolab/CRISPRitz
  license: GPL3
  summary: CRISPRitz, tool package for CRISPR experiments assessment and analysis.
