{% set version = "0.2.1" %}

package:
  name: neusomatic
  version: {{ version }}

source:
  url: https://github.com/bioinform/neusomatic/archive/v{{ version }}.tar.gz
  sha256: 362a490076c4f0887aa26b1df4928b38d46f8bdce3ceb19018c735cd78fd277f 

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - bzip2
    - numpy
    - scipy
    - imageio
    - pysam
    - pybedtools
    - samtools
    - tabix
    - bedtools
    - biopython
    - pytorch
    - torchvision
    - cudatoolkit
  run:
    - zlib
    - bzip2
    - numpy
    - scipy
    - imageio
    - pysam
    - pybedtools
    - samtools
    - tabix
    - bedtools
    - biopython
    - pytorch
    - torchvision
    - cudatoolkit

test:
  commands:
    - preprocess.py --help
    - call.py --help
    - postprocess.py --help

about:
  home: https://github.com/bioinform/neusomatic
  license: CC-BY-NC-SA-4.0
  license_file: LICENSE.md
  summary: |
    NeuSomatic is a tool for somatic mutation detection using deep 
    convolutional neural networks.
