{% set version = "0.99.8" %}
{% set name = "bodymapRat" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 2ca291eab17bb99ca05bb051d9d8ef90
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, BiocStyle, testthat
requirements:
  host:
    - 'bioconductor-experimenthub >=1.10.0,<1.11.0'
    - 'bioconductor-summarizedexperiment >=1.14.0,<1.15.0'
    - r-base
  run:
    - 'bioconductor-experimenthub >=1.10.0,<1.11.0'
    - 'bioconductor-summarizedexperiment >=1.14.0,<1.15.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: 'CC BY 4.0'
  summary: 'This package contains a SummarizedExperiment from the Yu et al. (2013) paper that performed the rat BodyMap across 11 organs and 4 developmental stages. Raw FASTQ files were downloaded and mapped using STAR. Data is available on ExperimentHub as a data package.'

