{% set name = "paleomix" %}
{% set version = "1.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MikkelSchubert/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7c46e8652f1c560aca81d865aec5cf7dc0309f9b3ef52c23f694f582963e33d0

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} setup.py install "

requirements:
  host:
    - python
  run:
    - python
    - adapterremoval
    - samtools
    - picard
    - bowtie2
    - bwa
    - mapdamage2
    - gatk
    - coloredlogs
    - pysam
    - ruamel.yaml
    - biopython
    - setproctitle

test:
  imports:
    - paleomix
  
  commands:
    - main.py --help

about:
  home: https://github.com/MikkelSchubert/paleomix
  license: GPL3
  summary: The PALEOMIX pipelines aid the rapid processing of High-Throughput Sequencing data.
  license_file: LICENSE

extra:
  recipe-maintainer:
    - gtrichard
  identifiers:
    - doi:10.1038/nprot.2014.063
