{% set version = "1.0.22" %}
{% set name = "org.Mxanthus.db" %}
{% set bioc = "3.10" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/annotation/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 47cc9afb55227c5ad053b3cc2cf87d5b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: DBI, RUnit, clusterProfiler
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.48.0,<1.49.0'
    - 'bioconductor-annotationhub >=2.18.0,<2.19.0'
    - r-base
  run:
    - 'bioconductor-annotationdbi >=1.48.0,<1.49.0'
    - 'bioconductor-annotationhub >=2.18.0,<2.19.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/annotation/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Genome wide annotation for Myxococcus xanthus DK 1622'
  description: 'Genome wide annotation for Myxococcus xanthus DK 1622, primarily based on mapping using Entrez Gene identifiers.'

