{% set name = "pypgatk" %}
{% set version = "0.0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "293a6bd6c20febb78a27f91f4894b88da7582c7dc29f2c732cdbaf1c95662398"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3
  run:
    - argcomplete
    - argh
    - asn1crypto
    - astroid
    - bcrypt
    - biopython
    - certifi
    - cffi
    - chardet
    - click
    - cryptography
    - gffutils
    - idna
    - isort
    - lazy-object-proxy
    - mccabe
    - numpy
    - paramiko
    - pyasn1
    - pycparser
    - pyfaidx
    - pylint
    - pynacl
    - pysftp
    - python >=3
    - pyvcf
    - pyyaml
    - requests
    - simplejson
    - six
    - typed-ast
    - urllib3
    - wrapt

test:
  imports:
    - pypgatk
    - pypgatk.cgenomes
    - pypgatk.commands
    - pypgatk.db
    - pypgatk.ensembl
    - pypgatk.proteomics
    - pypgatk.proteomics.db
    - pypgatk.tests
    - pypgatk.toolbox
  commands:
    - which pypgatk_cli.py
    - pypgatk_cli.py -h


about:
  home: "http://github.com/bigbio/py-pgatk"
  license: "Apache 2"
  license_family: "APACHE"
  summary: "The Pypgatk framework and library provides a set of tools to perform ProteoGenomics Analysis."
  doc_url: "https://pgatk.readthedocs.io/en/latest/pypgatk.html"
  dev_url: "https://github.com/bigbio/py-pgatk"

extra:
  recipe-maintainers:
    - ypriverol
