{% set version = "1.5.0" %}

package:
  name: gdc-client
  version: {{ version }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

source:
  url: https://github.com/NCI-GDC/gdc-client/archive/{{ version }}.tar.gz
  sha256: 2370d90f797342391f079df3a1ba8b01da05df138dd822ff531bcbf6754f4356

requirements:
  host:
    - python <3
    - parcel >=0.2,<1
    - lxml >=3,<4
    - pyyaml >=3,<4
    - jsonschema >=2,<3
    - pyopenssl >=17,<18
    - ndg-httpsclient >=0.4,<1
    - pyasn1 >=0.2,<1
    - zlib
  run:
    - python <3
    - parcel >=0.2,<1
    - lxml >=3,<4
    - pyyaml >=3,<4
    - jsonschema >=2,<3
    - pyopenssl >=17,<18
    - ndg-httpsclient >=0.4,<1
    - pyasn1 >=0.2,<1
    - zlib

test:
  commands:
    - gdc-client --help

about:
  home: https://gdc.cancer.gov/access-data/gdc-data-transfer-tool
  license: Apache v2
  summary: GDC Data Transfer Tool
