{% set version = "0.99.4" %}
{% set name = "adductData" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: c06b4b5a1239280e790c5f4326243645
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr (>= 1.15.1), rmarkdown (>= 1.5)
requirements:
  host:
    - 'bioconductor-annotationhub >=2.16.0,<2.17.0'
    - 'bioconductor-experimenthub >=1.10.0,<1.11.0'
    - r-base
  run:
    - 'bioconductor-annotationhub >=2.16.0,<2.17.0'
    - 'bioconductor-experimenthub >=1.10.0,<1.11.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'mzXML files from Grigoryan et al 2016 (Anal Chem).'

