{% set version = "1.25.0" %}
{% set name = "facsDorit" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 3e49063535ca855cbd7e1c14696cf502
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-prada >=1.60.0,<1.61.0'
    - r-base
  run:
    - 'bioconductor-prada >=1.60.0,<1.61.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-2
  summary: 'FACS example data for cell-based assays. This data is used in the examples and vignettes of the package prada.'

