{% set version = "1.24.0" %}
{% set name = "RIPSeekerData" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: e1f2cdfe28e7099ad8200657aa07452c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-ripseeker >=1.28.0,<1.29.0'
    - r-base
  run:
    - 'bioconductor-ripseeker >=1.28.0,<1.29.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-2
  summary: 'test data for RIPSeeker'
  description: 'The RIP-seq data in BAM format are the test data for the package RIPSeeker. The data correspond to two RIP-seq experiments, namely PRC2 and CCNT1. Raw data from NCBI Gene Expression Omnibus under accession numbers GSE17064 for PRC2 and in-house for CCNT1.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

