{% set name = "fastg2protlib" %}
{% set version = "0.1.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 3c78949f0e616ff63cae2721c0397d907b4b65a4fec588b1aa0b1532eb95c46e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - biopython
    - lxml
    - networkx
    - numpy
    - pip
    - pyteomics
    - python
  run:
    - biopython
    - lxml
    - networkx
    - numpy
    - pyteomics
    - python

test:
  imports:
    - fastg2protlib

about:
  home: "https://github.umn.edu/mcgo0092/fastg2protlib.git"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "FASTG sequences to a protein library"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
