{% set version = "0.8.3" %}

package:
  name: centroflye
  version: {{ version }}

source:
  git_url: https://github.com/seryrzu/centroFlye
  git_rev: 710f4abcaf6ec59ddf2149c7202f20de4ae45c0c
  md5: unused
  patches:
    - patch

build:
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  run:
    - python
    - python-edlib
    - networkx
    - numpy
    - regex
    - flye
    - ncrf

test:
  commands:
    - simulate_tandem_repeat.py

about:
  home: https://github.com/seryrzu/centroFlye/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An algorithm for centromere assembly using long error-prone reads
