{% set version = "0.8.3" %}

package:
  name: centroflye
  version: {{ version }}

source:
  git_url: https://github.com/seryrzu/centroFlye
  git_rev: 710f4abcaf6ec59ddf2149c7202f20de4ae45c0c
  md5: unused
  patches:
    - patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - zlib
  run:
    - python
    - python-edlib
    - biopython
    - networkx
    - numpy
    - regex
    - flye
    - ncrf
    - zlib

test:
  commands:
    - simulate_tandem_repeat.py 2>&1 | grep "usage:"

about:
  home: https://github.com/seryrzu/centroFlye/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An algorithm for centromere assembly using long error-prone reads

extra:
  skip-lints:
    - uses_vcs_url
