{% set name = "pp-sketchlib" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/johnlees/{{ name|lower }}.git
  git_rev: v{{ version }}
  sha256: f14633f8579841e71b8f9cd034247a7ba9fea94c

build:
  number: 0
  skip: True  # [py2k or win]
  script:
    # CUDA 10.1 moves some headers to `/usr/include`
    # So add that location last in the header search paths
    - export CFLAGS="${CFLAGS} -I/usr/include"  # [linux64]
    - export CPPFLAGS="${CPPFLAGS} -I/usr/include"  # [linux64]
    - export CXXFLAGS="${CXXFLAGS} -I/usr/include"  # [linux64]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  missing_dso_whitelist:
    - "*/libcuda.*"
  entry_points:
    - poppunk_sketch = pp_sketch.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - nvcc  # [linux64]
    - cmake
  host:
    - python
    - pip
    - pybind11
    - zlib
    - bzip2
    - eigen
    - armadillo
    - hdf5
    - openblas
  run:
    - python
    - numpy
    - zlib
    - bzip2
    - armadillo
    - hdf5
    - h5py
    - openblas

test:
  imports:
    - pp_sketch
  commands:
    - poppunk_sketch --version

about:
   home: https://github.com/johnlees/pp-sketchlib
   license: Apache-2.0
   license_family: APACHE
   license_file: LICENSE
   summary: Library of sketching functions used by PopPUNK

extra:
   skip-lints:
     - uses_vcs_url # includes submodules
