{% set name = "vmatch" %}
{% set version = "2.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://www.vmatch.de/distributions/vmatch-{{ version }}-Linux_x86_64-64bit.tar.gz # [linux64]
  sha256: 5e18d0dddf04e86dad193fcdde6e48f3901365932634125602d8808f35acf979
  url: http://www.vmatch.de/distributions/vmatch-{{ version }}-Darwin_i386-64bit.tar.gz # [osx]
  sha256: 39695c7d20158446ff27656f9ba415097052570bcc67ed12efec376fc3b0b4c6

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make
  run:
    - perl >=5.10,<6

test:
  files:
    - ../blast/test.fa 
    - ../blast/testdatabase.fa
  commands:
    # (see run_test.sh for remainder of tests)
    - mkvtree -help > /dev/null
    - mkdna6idx -help > /dev/null
    - vmatch -help > /dev/null
    - vmatchselect -help > /dev/null
    - matchcluster -help > /dev/null
    - vseqinfo -help > /dev/null
    - vseqselect -help > /dev/null
    - vstree2tex -help > /dev/null
    - vsubseqselect -help > /dev/null
    - chain2dim -help > /dev/null
    - vmigrate.sh -help > /dev/null
    - vendian -help > /dev/null
    - cleanpp.sh -help > /dev/null
    - upgradeprj.pl -help > /dev/null
    - repfind.pl -help > /dev/null
    - Vmatchtrans.pl -help > /dev/null

about:
  home: http://www.vmatch.de/
  license: Unknown
  license_family: OTHER
  summary: The Vmatch large scale sequence analysis software

extra:
  identifiers:
    - biotools:vmatch
