{% set version = "0.3.12" %}

package:
  name: hap.py
  version: '{{ version }}'

source:
  url: https://github.com/Illumina/hap.py/archive/v{{ version }}.tar.gz
  sha256: 1ba8d0245b8c7d6a68ca5b78ab8d0d87104e9a3b36c86169319c5add2395b6a5

build:
  number: 0
  skip: true # [not py27 or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - autoconf
    - automake
  host:
    - boost-cpp
    - python
    - pip
    - zlib
    - cython
    - scipy
    - numpy
    - pandas
    - pybedtools
    - pysam
    - bx-python
    - htslib
  run:
    - python
    - samtools
    - bcftools
    - scipy
    - numpy
    - pandas
    - pybedtools
    - pysam
    - bx-python
    - htslib

test:
  commands:
    - hap.py -h
    - som.py -h

about:
  home: https://github.com/Illumina/hap.py
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Haplotype VCF comparison tools
