{% set name = "cytoscape" %}
{% set version = "3.8.0" %}
{% set sha256 = "726b4bf59c6fa9406d093fb03c1847f2dc432d3a4f975862b6aa4140a0ca9aba" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/cytoscape/cytoscape/releases/download/{{ version }}/Cytoscape_{{ version|replace(".","_") }}_unix.sh
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - gettext
  host:
    # Cytoscape requires Java 8 (9+ not supported)
    - openjdk=8
    - fontconfig
    - freetype
    - font-ttf-dejavu-sans-mono
  run:
    - openjdk=8
    - xorg-libxtst
    - fontconfig
    - freetype
    - font-ttf-dejavu-sans-mono

test:
  commands:
    - "cytoscape.sh -v"

about:
  home: https://cytoscape.org
  license: LGPL
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Cytoscape: an open source platform for network analysis and visualization.'
  dev_url: https://github.com/cytoscape/cytoscape

extra:
  identifiers:
    - biotools:cytoscape
    - doi:10.1101/gr.1239303
