{% set name = "treekin" %}
{% set version = "0.5.0" %}
{% set sha256 = "e4e707134c4396e37f11206be6ab2d79799447118702e97a02de68d1cf02e66c" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0

source:
  url: https://www.tbi.univie.ac.at/~ronny/winterschool/Treekin-0.5.0.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - mlapack
  run:
    - mlapack

test:
  commands:
    - treekin --version

about:
  home: https://www.tbi.univie.ac.at/RNA/Treekin/
  license: GPL
  license_file: COPYING
  summary: "Compute folding dynamics on coarse grained version of an energy landscape by numeric integration of a Markov process"


