{% set name = "indra" %}
{% set version = "1.13.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6aa5b9591ae2c058cadf65cd8ef70cf0bf1375844e9e7968faa8a65032f22c86

build:
  number: 0
  entry_points:
    - indra-machine = indra.tools.machine.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - future
    - ipython
    - jinja2
    - lxml
    - ndex2 ==2.0.1
    - networkx >=2
    - objectpath
    - pandas
    - protmapper >=0.0.6
    - pysb >=1.3.0
    - python >=3
    - rdflib ==4.2.1
    - requests >=2.11

test:
  imports:
    - indra
    - indra.assemblers
    - indra.assemblers.cag
    - indra.assemblers.cx
    - indra.assemblers.cyjs
    - indra.assemblers.english
    - indra.assemblers.figaro
    - indra.assemblers.graph
    - indra.assemblers.html
    - indra.assemblers.index_card
    - indra.assemblers.kami
    - indra.assemblers.pybel
    - indra.assemblers.pysb
    - indra.assemblers.sbgn
    - indra.assemblers.sif
    - indra.assemblers.tsv
    - indra.belief
    - indra.benchmarks
    - indra.databases
    - indra.explanation
    - indra.literature
    - indra.mechlinker
    - indra.preassembler
    - indra.resources
    - indra.resources.famplex
    - indra.sources
    - indra.sources.bel
    - indra.sources.biopax
    - indra.sources.cwms
    - indra.sources.eidos
    - indra.sources.geneways
    - indra.sources.hprd
    - indra.sources.hume
    - indra.sources.index_cards
    - indra.sources.indra_db_rest
    - indra.sources.lincs_drug
    - indra.sources.ndex_cx
    - indra.sources.reach
    - indra.sources.rlimsp
    - indra.sources.sofia
    - indra.sources.sparser
    - indra.sources.tas
    - indra.sources.tees
    - indra.sources.trips
    - indra.sources.trrust
    - indra.statements
    - indra.tests
    - indra.tools
    - indra.tools.machine
    - indra.tools.reading
    - indra.tools.reading.pmid_reading
    - indra.tools.reading.starcluster_reading
    - indra.tools.reading.util
    - indra.util
  commands:
    - indra-machine --help

about:
  home: http://github.com/sorgerlab/indra
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Integrated Network and Dynamical Reasoning Assembler
  description: NDRA (Integrated Network and Dynamical Reasoning Assembler) is an automated model assembly system, originally developed for molecular systems biology and currently being generalized to other domains.
