{% set version = "1.15.0" %}
{% set name = "diggitdata" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: 9ffb3f1b15846b089d03b1227e178f91
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-biobase >=2.44.0,<2.45.0'
    - 'bioconductor-viper >=1.17.0,<1.18.0'
    - r-base
  run:
    - 'bioconductor-biobase >=2.44.0,<2.45.0'
    - 'bioconductor-viper >=1.17.0,<1.18.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'This package provides expression profile and CNV data for glioblastoma from TCGA, and transcriptional and post-translational regulatory networks assembled with the ARACNe and MINDy algorithms, respectively.'

