{% set version = "1.13.0" %}
{% set name = "TimerQuant" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: efad56d11070f4bdef1038f03e54635e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, reshape2, knitr, shinyBS
requirements:
  host:
    - r-base
    - r-desolve
    - r-dplyr
    - r-ggplot2
    - r-gridextra
    - r-locfit
    - r-shiny
  run:
    - r-base
    - r-desolve
    - r-dplyr
    - r-ggplot2
    - r-gridextra
    - r-locfit
    - r-shiny
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Supplementary Data package for tandem timer methods paper by Barry et al. (2015) including TimerQuant shiny applications.'

