{% set version = "1.2.3" %}

package:
  name: xmatchview
  version: {{ version }}

source:
  url: https://github.com/bcgsc/xmatchview/archive/v{{ version }}.tar.gz
  sha256: 774dd0f07946511b853eed167d3fbff56f72fa0ee0f4a586207904246789042e

build:
  noarch: generic
  number: 0

requirements:
  run:
    - python <3
    - pip
    - pillow
    - minimap2

test:
  commands:
    - xmatchview.py 2>&1 | grep {{ version }}

about:
  summary: Genome sequence alignment visualization
  home: http://www.bcgsc.ca/platform/bioinfo/software/xmatchview
  license: GNU General Public License v3.0
  license_file: LICENSE
  doc_url: https://github.com/bcgsc/xmatchview

extra:
  recipe-maintainers:
    - zyxue
