package:
  name: plant_tribes_gene_family_phylogeny_builder
<<<<<<< HEAD
  version: "1.0.3"

source:
  url: https://github.com/dePamphilis/PlantTribes/archive/v1.0.3.tar.gz
  md5: fadbcc5f105eb05156e5068380840460

build:
  noarch: generic
  number: 2
=======
  version: "1.0.4"

source:
  url: https://github.com/dePamphilis/PlantTribes/archive/v1.0.4.tar.gz
  sha256: 095c6fe1f12e034d348ee029389e62dfb3004e201a581e5d5c46976318ced8ec

build:
  noarch: generic
  number: 0
>>>>>>> bioconductor_3.10

requirements:
  run:
    - fasttree >=2,<3
    - perl
    - raxml >=8,<9

test:
  commands:
    - GeneFamilyPhylogenyBuilder 2>&1 | grep PHYLOGENETIC

about:
  home: 'https://github.com/dePamphilis/PlantTribes'
  summary: 'Gene family phylogeny builder pipeline'
  license: GNU General Public License v3 (GPLv3)
