{% set version = "1.3.9.1" %}

package:
  name: moabs
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/sunnyisgalaxy/moabs/archive/v{{ version }}.tar.gz
  sha256: 27aefa5dce331f33995c542c10370fc43290cec8bf192fea258cd69683be15ca

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
  host:
    - zlib
    - perl-config-simple
    - ncurses
    - boost-cpp
    - perl
    - wget
    - r-base
    - r-ggplot2
    - r-gridextra
  run:
    - zlib
    - perl-config-simple
    - ncurses
    - boost-cpp
    - perl
    - wget
    - r-base
    - r-ggplot2
    - r-gridextra
    - libis >=0.0.9

test:
  commands:
    - moabs --help

about:
  home: https://github.com/sunnyisgalaxy/moabs
  license: MIT
  summary: Methylation analysis on Bisulfite-Sequencing reads
