{% set version = "1.19.1" %}
{% set name = "geneLenDataBase" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: a6ae5fa0cb02238683cf569c1deadc10
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-genomicfeatures >=1.36.0,<1.37.0'
    - 'bioconductor-rtracklayer >=1.44.0,<1.45.0'
    - r-base
  run:
    - 'bioconductor-genomicfeatures >=1.36.0,<1.37.0'
    - 'bioconductor-rtracklayer >=1.44.0,<1.45.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: 'LGPL (>= 2)'
  summary: 'Length of mRNA transcripts for a number of genomes and gene ID formats, largely based on UCSC table browser'
extra:
  parent_recipe:
    name: bioconductor-genelendatabase
    path: recipes/bioconductor-genelendatabase
    version: 1.16.0

