{% set version = "1.1.1" %}
{% set name = "qPLEXdata" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 8b14ddd2d9ae4344fe25ad420d928a27
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-msnbase >=2.10.0,<2.11.0'
    - 'bioconductor-qplexanalyzer >=1.2.0,<1.3.0'
    - r-base
    - r-dplyr
    - r-knitr
  run:
    - 'bioconductor-msnbase >=2.10.0,<2.11.0'
    - 'bioconductor-qplexanalyzer >=1.2.0,<1.3.0'
    - r-base
    - r-dplyr
    - r-knitr
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-2
  summary: 'qPLEX-RIME and Full proteome TMT mass spectrometry datasets.'

