{% set version = "2.10.5" %}
{% set bioconda_version = "2.10.5" %}
{% set ngs_version = "2.10.5" %}

package:
  name: sra-tools
  version: '{{ bioconda_version }}'

source:
  - url: https://github.com/ncbi/sra-tools/archive/{{version}}.tar.gz
    sha256: bc98ab1338461590033f92230494b669f32e0e6f01fcb4914a3505dcee008c18
    folder: sra-tools
    #patches:
    #  - skip_config_interactive.diff
  - url: https://github.com/ncbi/ncbi-vdb/archive/{{version}}.tar.gz
    sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    folder: ncbi-vdb
  - url: https://github.com/ncbi/ngs/archive/{{ngs_version}}.tar.gz
    sha256: c39ee65a625e3646e0212c5d8be846e45d368c644a053d3b54cf63f53853f02f
    folder: ngs

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ncbi-ngs-sdk
    - libxml2
    - hdf5
    - perl
  run:
    - perl
    - ncbi-ngs-sdk
    - libxml2
    - hdf5
    - perl-xml-libxml
    - perl-uri

test:
  commands:
    - fastq-dump --help > /dev/null
    - prefetch --help > /dev/null
    - sam-dump --help > /dev/null
    - sra-pileup --help > /dev/null
    - vdb-config --help > /dev/null
    - vdb-decrypt --help > /dev/null
    - fastq-dump -N 1 -X 1 SRR000001 && grep '@SRR000001.1' SRR000001.fastq
    - fasterq-dump --help > /dev/null

about:
  home: https://github.com/ncbi/sra-tools
  license: Public Domain
  summary: SRA Toolkit and SDK from NCBI
  description:  |
    The SRA Toolkit and SDK from NCBI is a collection of tools and libraries
    for using data in the INSDC Sequence Read Archives.

extra:
  notes: 'After installation, you should run the configuration tool: ./vdb-config
    -i. This tool will setup your download/cache area for downloaded files and references.'
