{% set version = "1.3.0" %}
{% set name = "MetaGxOvarian" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 8a2b2b5b57bc0674ac40a7c9cbf5e92c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: testthat, xtable
requirements:
  host:
    - 'bioconductor-annotationhub >=2.16.0,<2.17.0'
    - 'bioconductor-biobase >=2.44.0,<2.45.0'
    - 'bioconductor-experimenthub >=1.10.0,<1.11.0'
    - 'bioconductor-impute >=1.58.0,<1.59.0'
    - r-base
    - r-lattice
  run:
    - 'bioconductor-annotationhub >=2.16.0,<2.17.0'
    - 'bioconductor-biobase >=2.44.0,<2.45.0'
    - 'bioconductor-experimenthub >=1.10.0,<1.11.0'
    - 'bioconductor-impute >=1.58.0,<1.59.0'
    - r-base
    - r-lattice
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'A collection of Ovarian Cancer Transcriptomic Datasets that are part of the MetaGxData package compendium.'

