{% set version = "0.2.0" %}

package:
  name: vsnp
  version: {{ version }}

build:
  number: 0
  noarch: generic

source:
  url: https://github.com/USDA-VS/vSNP/archive/{{ version }}.tar.gz
  sha256: 39bd6ec96222fceff5e16a948fbfc30a468c217ccc86bdbbeb442786aae70ae2

requirements:
  run:
  - python >=3.6
  - biopython
  - dask
  - pysam
  - freebayes
  - regex
  - pandas
  - pyvcf
  - xlsxwriter
  - bwa
  - samtools
  - picard
  - abyss
  - raxml
  - humanize
  - vcflib
  - matplotlib
  - xlrd

test:
  commands:
    - vSNP_step1.py -h

about:
  home: https://github.com/USDA-VS/vSNP
  license: GPL3
  license_file: LICENSE
  summary: Rapidly call, validate, and compare SNPs from FASTQ files in a timely manner utilizing large data sets.
  dev_url: https://github.com/USDA-VS/vSNP
