{% set version = '0.0.5' %}

package:
  name: r-prestor
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://bitbucket.org/javh/prototype-prestor/get/Version {{ version }} - Prerelease.tar.bz2
  sha256: 6d4e3ec53d9b3ec8b5e32d6ace0ed9ac7443061c27a04ec8869c3a6e683c19ef

build:
  number: 1
  noarch: generic

requirements:
  host:
    - r-alakazam >=0.2.11
    - r-base >=3.4.1
    - r-bibtex
    - r-captioner
    - r-devtools
    - r-dplyr
    - r-ggplot2 >=2
    - r-hexbin
    - r-optparse
    - r-rmarkdown
    - r-roxygen2
    - r-tidyr

  run:
    - r-alakazam >=0.2.11
    - r-base >=3.4.1
    - r-bibtex
    - r-captioner
    - r-devtools
    - r-dplyr
    - r-ggplot2 >=2
    - r-hexbin
    - r-optparse
    - r-rmarkdown
    - r-roxygen2
    - r-tidyr
    - r-knitr
    - r-lazyeval

test:
  commands:
    - Rscript -e "library(prestor)"

about:
  home: https://bitbucket.org/javh/prototype-prestor
  summary: 'A prototype package for generating quality control plots from pRESTO output.'
  license: Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
  license_url: https://creativecommons.org/licenses/by-sa/4.0/legalcode
  license_family: OTHER
extra:
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - bioconda/r
