package:
  name: kissplice
  version: '2.5.1'

source:
  url: "ftp://pbil.univ-lyon1.fr/pub/logiciel/kissplice/download/kissplice-2.5.1.tar.gz"
  sha256: "f6f014adb27cb022c853420096d06802e8e16212d2bc835fdd6898a07d095e64"

build:
  number: 0
  skip: True # [osx or py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - python
  run:
    - python

test:
  commands:
    - kissplice -h

about:
  home: http://kissplice.prabi.fr
  license: CeCILL license
  summary: A local transcriptome assembler for SNPs, indels and AS events
