package:
  name: kissplice
  version: '2.5.0'

source:
  url: "ftp://pbil.univ-lyon1.fr/pub/logiciel/kissplice/download/kissplice-2.5.0.tar.gz"
  sha256: "13f85abef44d99db004f9e58c57974483dda8eade41a38710c4f83c4e94131c8"

build:
  number: 0
  skip: True # [osx or py3k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - python >=3
  run:
    - python >=3

test:
  commands:
    - kissplice -h

about:
  home: http://kissplice.prabi.fr
  license: CeCILL license
  summary: A local transcriptome assembler for SNPs, indels and AS events
