{% set name = "Gcluster" %}
{% set version = "2.0.1" %}
{% set sha256 = "ea6af683ff19494199d71cb3e64ff86298ca58665dd2df24c87e140827c5a82f" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
    url: https://github.com/Xiangyang1984/Gcluster/archive/Gcluster-v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 1
  noarch: generic

requirements:
  run:
    - mcl
    - blast
    - perl-gd
    - perl-gd-svg
    - perl-svg
    - perl-bioperl-core
    #- git

about:
  home: 'http://www.microbialgenomic.com/Gcluster_tool.html'
  summary: 'Gcluster is a simple-to-use tool for visualizing and comparing genome contexts for numerous genomes.'
  license: perl_5
