{% set INTARNA_VERSION = "3.1.4" %}
{% set INTARNA_SHA256  = "da6e61d1f642f3b2763e2638056e2617c841f36005bff8f98dc1b47b7237d9e8" %}
{% set VRNA_VERSION = "2.4.14" %}

package:
  name: intarna
  version: {{INTARNA_VERSION}}

about:
  home: https://github.com/BackofenLab/IntaRNA
  license: MIT
  summary: Efficient RNA-RNA interaction prediction incorporating seeding and accessibility of interacting sites

build:
  number: 0

source:
  url: "https://github.com/BackofenLab/IntaRNA/releases/download/v{{INTARNA_VERSION}}/intaRNA-{{INTARNA_VERSION}}.tar.gz"
  sha256: {{INTARNA_SHA256}}

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - zlib
    - viennarna >={{VRNA_VERSION}}*,<3.*
    - pkgconfig
    - doxygen
    - perl
    - llvm-openmp # [osx]
  run:
    - boost-cpp
    - llvm-openmp # [osx]
    - zlib

test:
  commands:
    - IntaRNA -h
    - IntaRNA -t CCCCCCCCGGGGGGGGGGGGGG -q CCCCCCC

extra:
  identifiers:
    - biotools:intarna
    - doi:10.1093/nar/gkx279
    - doi:10.1093/bioinformatics/btn544
    - doi:10.1093/nar/gky329
  recipe-maintainers:
    - martin-raden
    - BackofenLab

