{% set name = "perl-text-csv_xs" %}
{% set version = "1.41" %}
{% set sha256 = "0e4b7be423c02f09135a75082cb00136ff6a69cff25b012089048ea030f173ab" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/H/HM/HMBRAND/Text-CSV_XS-1.41.tgz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-extutils-makemaker
    - perl-test-harness
    - perl-text-csv

  run:
    - perl
    - perl-test-harness
    - perl-text-csv

test:
  imports:
    - Text::CSV_XS

about:
  home: https://metacpan.org/pod/Text::CSV_XS
  license: perl_5
  summary: 'Text::CSV_XS - comma-separated values manipulation routines'
