{% set version = "1.19.0" %}
{% set name = "DREAM4" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: a389c5e23fc7f46f714548ec4be33c7e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: RUnit, networkBMA
requirements:
  host:
    - 'bioconductor-summarizedexperiment >=1.14.0,<1.15.0'
    - r-base
  run:
    - 'bioconductor-summarizedexperiment >=1.14.0,<1.15.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL
  summary: 'Simulated expression data for five 10-node, and five 100-node networks, with associated data (including solutions) from the 2009 DREAM4 challenge.'

