{% set version = "0.4" %}
{% set sha256 = "e5ad809e4f627737128e4cbd400d8486b6adb45048cab55fb1f1926410910ee6" %}

package:
  name: boink
  version: '{{version}}'

source:
  url: https://github.com/camillescott/boink/archive/v{{ version }}.tar.gz
  sha256: '{{sha256}}'

build:
  number: 0
  script:
    - mkdir build && cd build && BOINK_VERSION={{version}} cmake .. -DCMAKE_BUILD_TYPE=Release && make install

requirements:
  build:
    - '{{compiler("c")}}'
    - '{{compiler("cxx")}}'
    - cmake
  host:
    - python >=3.6
    - cppyy >=1.5.5
    - clangdev =8.0.1
    - libcxx
    - libstdcxx-ng
    - libgcc-ng
    - openmp
    - zlib
    - python-clang
  run:
    - python >=3.6
    - zlib
    - screed
    - blessings
    - pyfiglet
    - py-cpuinfo
    - numpy

test:
  imports:
    - boink

about:
  home: https://github.com/camillescott/boink
  license: MIT
  summary: streaming de Bruijn graph compaction and sketching.
