{% set version = "3.9.1" %}

package:
  name: spades
  version: {{ version }}

source:
  url: http://spades.bioinf.spbau.ru/release3.9.1/SPAdes-3.9.1-Linux.tar.gz  # [linux]
  md5: 095f4f7dd0e6496156df5d7c9419a70f                                      # [linux]
  url: http://spades.bioinf.spbau.ru/release3.9.1/SPAdes-3.9.1-Darwin.tar.gz # [osx]
  md5: d41d8cd98f00b204e9800998ecf8427e                                      # [osx]

build:
  number: 0
  skip: True  # [py36]

requirements:
  run:
    - python

test:
  commands:
    - spades.py --test && rm -rf spades_test

about:
  home: http://cab.spbu.ru/software/spades/
  license: GPLv2
  license_family: GPL
  license_file: share/spades/LICENSE
  summary: SPAdes (St. Petersburg genome assembler) is intended for both standard isolates and single-cell MDA bacteria assemblies.
  dev_url: https://github.com/ablab/spades
  doc_url: http://cab.spbu.ru/files/release{{version}}/manual.html

extra:
  identifiers:
    - biotools:Spades
    - doi:10.1089/cmb.2012.0021
