{% set name = "ribolands" %}
{% set version = "0.6" %}
{% set sha256 = "9dda471bdefea5cbc67743307964e8ec0acf51751fc7c9168b69060c1c3d3ff4" %}

package:
  name: {{ name }}
  version: {{ version }}

about:
  home: https://github.com/bad-ants-fleet/ribolands
  license: MIT
  summary: "Energy landscapes and folding kinetics of nucleic acids"

build:
  number: 0

source:
  url: https://www.tbi.univie.ac.at/~ronny/winterschool/ribolands-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - python
  host:
  run:
    - python
    - viennarna
    - pandas
    - networkx
    - matplotlib
    # -crnsimulator (https://github.com/bad-ants-fleet/crnsimulator)
    - treekin ==0.5.1

test:
  commands:
    - python DrTransformer.py --version
    - python BarMap.py -h > /dev/null

